enum StatusTypes {
  IDLE = "IDLE",
  UPDATED = "UPDATED",
  PENDING = "PENDING",
  FULLFILLED = "FULLFILLED",
  REJECTED = "REJECTED",
  REFUSED = "REFUSED",
}

enum ProfileStateTypes {
  READ_USER = "READING_USER",
  ERROR_READ_USER = "ERROR_READ_USER",

  UPDATE_USER = "UPDATING_USER",
  ERROR_UPDATE_USER = "ERROR_UPDATING_USER",

  CREATE_USER = "CREATING_USER",
  ERROR_CREATE_USER = "ERROR_CREATING_USER",
}
